print("this is a calculator")
print("with maths would you like to do (1) add (2) multiply (3) divition (4) subtract")
user_choice = input("->")

if user_choice == "1":
    print('you picked addtion')
    print('this adds two numbers')
    x = float(input('num1: '))
    print(x)
    a = float(input('num2: '))
    temp_output=float(x + a)
    print(temp_output)
elif user_choice == "2":
    print('you picked multiplying')
    print('this multiplys two numbers')
    x = float(input('num1: '))
    print(x)
    a = float(input('num2: '))
    temp_output=float(x * a)
    print(temp_output)
elif user_choice == "3":
    print('you picked dividing')
    print('this divides two numbers')
    x = float(input('num1: '))
    print(x)
    a = float(input('num2: '))
    temp_output=float(x / a)
    print(temp_output)
elif user_choice == "4":
    print('you picked subtract')
    print('this subtracts two numbers')
    x = float(input('num1: '))
    print(x)
    a = float(input('num2: '))
    temp_output=float(x - a)
    print(temp_output)
else:
    print("error")